[package]
name = "merkle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
fastcrypto.workspace = true
serde.workspace = true
proptest.workspace = true
sui-types.workspace = true
bcs.workspace = true


typed-store.workspace = true
typed-store-derive.workspace = true
rocksdb.workspace = true
eyre.workspace = true
tempfile.workspace = true
tokio.workspace = true
sui-storage.workspace = true
itertools.workspace = true
