[package]
name = "simulacrum-node"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
tap.workspace = true
simulacrum.workspace = true
sui-types.workspace = true
