processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-54:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 10510800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 56-58:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3032400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'create-checkpoint'. lines 60-60:
Checkpoint created: 1

task 4 'run-graphql'. lines 62-83:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x68d58b103ea00d976d7f684cd231bb192de745e7a76e7583406d2046b0f489c6::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  42,
                                  5,
                                  157,
                                  209,
                                  68,
                                  156,
                                  200,
                                  207,
                                  182,
                                  167,
                                  45,
                                  161,
                                  164,
                                  98,
                                  140,
                                  20,
                                  1,
                                  130,
                                  54,
                                  115,
                                  120,
                                  116,
                                  199,
                                  217,
                                  146,
                                  242,
                                  145,
                                  13,
                                  250,
                                  206,
                                  40,
                                  97
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  42,
                                  5,
                                  157,
                                  209,
                                  68,
                                  156,
                                  200,
                                  207,
                                  182,
                                  167,
                                  45,
                                  161,
                                  164,
                                  98,
                                  140,
                                  20,
                                  1,
                                  130,
                                  54,
                                  115,
                                  120,
                                  116,
                                  199,
                                  217,
                                  146,
                                  242,
                                  145,
                                  13,
                                  250,
                                  206,
                                  40,
                                  97
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      42,
                                      5,
                                      157,
                                      209,
                                      68,
                                      156,
                                      200,
                                      207,
                                      182,
                                      167,
                                      45,
                                      161,
                                      164,
                                      98,
                                      140,
                                      20,
                                      1,
                                      130,
                                      54,
                                      115,
                                      120,
                                      116,
                                      199,
                                      217,
                                      146,
                                      242,
                                      145,
                                      13,
                                      250,
                                      206,
                                      40,
                                      97
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            },
                            {
                              "name": "f8",
                              "value": {
                                "Variant": {
                                  "name": "A",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f9",
                              "value": {
                                "Variant": {
                                  "name": "B",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f10",
                              "value": {
                                "Variant": {
                                  "name": "C",
                                  "fields": [
                                    {
                                      "name": "pos0",
                                      "value": {
                                        "Number": "45"
                                      }
                                    }
                                  ]
                                }
                              }
                            },
                            {
                              "name": "f11",
                              "value": {
                                "Variant": {
                                  "name": "D",
                                  "fields": [
                                    {
                                      "name": "x",
                                      "value": {
                                        "Number": "46"
                                      }
                                    }
                                  ]
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x2a059dd1449cc8cfb6a72da1a4628c14018236737874c7d992f2910dface2861",
                          "f0": "0x2a059dd1449cc8cfb6a72da1a4628c14018236737874c7d992f2910dface2861",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0x2a059dd1449cc8cfb6a72da1a4628c14018236737874c7d992f2910dface2861"
                          ],
                          "f7": 44,
                          "f8": {
                            "A": {}
                          },
                          "f9": {
                            "B": {}
                          },
                          "f10": {
                            "C": {
                              "pos0": 45
                            }
                          },
                          "f11": {
                            "D": {
                              "x": "46"
                            }
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  45,
                                  49,
                                  162,
                                  80,
                                  79,
                                  60,
                                  146,
                                  140,
                                  146,
                                  44,
                                  231,
                                  124,
                                  212,
                                  191,
                                  204,
                                  3,
                                  96,
                                  99,
                                  159,
                                  148,
                                  203,
                                  123,
                                  240,
                                  155,
                                  95,
                                  71,
                                  130,
                                  121,
                                  67,
                                  155,
                                  159,
                                  183
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999995967600"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x2d31a2504f3c928c922ce77cd4bfcc0360639f94cb7bf09b5f478279439b9fb7",
                          "balance": {
                            "value": "299999995967600"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
