name: Docs

on:
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
  workflow_dispatch:

jobs:
  docs:
    name: Generate crate documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # pin@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - name: Generate documentation
        env:
          RUSTC_BOOTSTRAP: 1
          RUSTDOCFLAGS: "--enable-index-page -Zunstable-options"
        run: |
          cargo doc --workspace --no-deps

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # pin@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/doc
          force_orphan: true
